drop table if exists planets;
drop table if exists lords;
create table lords (
                       id integer generated by default as  identity (start with 1) primary key,
                       name varchar(255),
                       age int
);

create table planets(
                        id integer generated by default as  identity (start with 1) primary key ,
                        name varchar(255),
                        lord_id int references lords(id)
);

insert into lords (name, age)
VALUES ('first', 35), ('second', 45), ('third', 55);

insert into planets (name, lord_id)
VALUES ('mars', 1), ('jupiter', 2), ('saturn', 2);